USE centromedico;
-- MOSTRAR TODAS LAS TABLAS QUE HAY EN LA BASE DE DATOS
SHOW TABLES FROM centromedico;

SELECT * FROM HABITACION;

SELECT * FROM PACIENTE;

SELECT * FROM LOG_ACTIVIDAD;

-- CONTAMOS LA CANTIDAD DE PACIENTES:
SELECT COUNT(*) FROM PACIENTE;

-- SELECCIONAR LA EDAD DE LOS PACIENTES MAYORES DE 50 ANIOS:
SELECT * FROM PACIENTE WHERE edad > 50;

-- SELECCIONAR LA EDAD DE LOS PACIENTES MAYORES DE 50 ANIOS:
SELECT * FROM PACIENTE WHERE edad > 50 ORDER BY edad DESC;

-- SELECCIONAR LA CANTIDAD DE PACIENTES MUJERES:
SELECT COUNT(*) FROM PACIENTE WHERE genero='Femenino\r';

-- SELECCIONAR LA CANTIDAD DE PACIENTES MUJERES MENORES A 50 ANIOS:
-- DOS CONDICIONES SE VEN ASI:
SELECT * FROM PACIENTE WHERE genero='Femenino\r' AND edad<50;

-- SELECCIONAR TODOS LOS HOMBRES QUE TENGAN UNA EDAD ENTRE 20 Y 50 ANIOS
SELECT * 
FROM PACIENTE 
WHERE 
	genero='Masculino\r' AND 
    edad>20 AND 
    edad<50 
ORDER BY 
	edad 
ASC;
